CREATE TABLE IF NOT EXISTS "TIPOS_ACTIVIDAD" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CODIGO" VARCHAR(40) NOT NULL UNIQUE,
    "NOMBRE" VARCHAR(120) NOT NULL,
    "DESCRIPCION" VARCHAR(255) NOT NULL,
    "COLOR_FONDO" VARCHAR(20) NOT NULL,
    "COLOR_TEXTO" VARCHAR(20) NOT NULL,
    "ICONO" VARCHAR(80) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "ACTIVIDADES_ESCOLARES" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TIPO_ACTIVIDAD_ID" BIGINT NOT NULL REFERENCES "TIPOS_ACTIVIDAD"("ID"),
    "TITULO" VARCHAR(160) NOT NULL,
    "DESCRIPCION" TEXT,
    "FECHA" DATE NOT NULL,
    "FECHA_FIN" DATE,
    "HORA" TIME,
    "UBICACION" VARCHAR(180),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO "TIPOS_ACTIVIDAD" ("CODIGO", "NOMBRE", "DESCRIPCION", "COLOR_FONDO", "COLOR_TEXTO", "ICONO", "ACTIVO")
VALUES
    ('ACADEMICA', 'Academica', 'Actividades relacionadas con clases, evaluaciones y entregas.', '#DCEBFB', '#1F5DA8', 'menu_book', TRUE),
    ('DEPORTIVA', 'Deportiva', 'Eventos y actividades deportivas del establecimiento.', '#E5F2D6', '#47771A', 'sports_soccer', TRUE),
    ('CULTURAL', 'Cultural', 'Actividades artisticas, ferias y presentaciones culturales.', '#FDEACF', '#A26112', 'theater_comedy', TRUE),
    ('INSTITUCIONAL', 'Institucional', 'Reuniones y actividades de coordinacion institucional.', '#E9E5FB', '#5447B7', 'account_balance', TRUE),
    ('TRANSVERSAL', 'Transversal (Todos los cursos)', 'Actividad publicada para todos los cursos del calendario institucional.', '#E0F2FE', '#0F4C81', 'groups', TRUE),
    ('VACACIONES', 'Vacaciones', 'Periodo sin clases que aplica para todos los cursos.', '#DBEAFE', '#1D4ED8', 'beach_access', TRUE),
    ('FERIADO', 'Feriado', 'Dia feriado sin clases para todos los cursos.', '#FCE7F3', '#BE185D', 'celebration', TRUE),
    ('SUSPENSION', 'Suspension', 'Suspension institucional de clases para todos los cursos.', '#E2E8F0', '#475569', 'event_busy', TRUE),
    ('SOCIAL', 'Social', 'Actividades de convivencia y encuentros con la comunidad.', '#FBE1E8', '#B13B68', 'favorite', TRUE)
ON CONFLICT ("CODIGO") DO UPDATE
SET
    "NOMBRE" = EXCLUDED."NOMBRE",
    "DESCRIPCION" = EXCLUDED."DESCRIPCION",
    "COLOR_FONDO" = EXCLUDED."COLOR_FONDO",
    "COLOR_TEXTO" = EXCLUDED."COLOR_TEXTO",
    "ICONO" = EXCLUDED."ICONO",
    "ACTIVO" = TRUE;

DELETE FROM "ACTIVIDADES_ESCOLARES"
WHERE "TITULO" IN (
    'Ingreso de estudiantes',
    'Comienzo de clases y nivelacion',
    'Culto de apertura y presentacion',
    'Dia de la Mujer y reunion de apoderados',
    'Actividades breves Semana Santa',
    'Inicio inscripcion examenes libres Mineduc',
    'Feriado Viernes Santo',
    'Evaluacion Lectoescritura Pre Kinder',
    'Evaluacion Matematicas Pre Kinder',
    'Evaluacion Lectoescritura Kinder',
    'Evaluacion Matematicas Kinder',
    'Evaluacion Ciencias 1 Basico',
    'Evaluacion Lenguaje 1 Basico',
    'Evaluacion Matematicas 1 Basico',
    'Evaluacion Historia 1 Basico',
    'Guia evaluada Historia 3 Basico',
    'Guia evaluada Ciencias Naturales 3 Basico',
    'Prueba de Lenguaje 3 Basico',
    'Guia evaluada Historia 4 Basico',
    'Guia evaluada Ciencias 4 Basico',
    'Prueba de Lenguaje 4 Basico',
    'Guia evaluada Historia 5 Basico',
    'Guia evaluada Ciencias 5 Basico',
    'Prueba de Lenguaje 5 Basico',
    'Guia evaluada Historia 6 Basico',
    'Guia evaluada Ciencias 6 Basico',
    'Prueba de Lenguaje 6 Basico',
    'Examen Matematicas',
    'Reunion Docentes',
    'Laboratorio Ciencias',
    'Proyecto Arte',
    'Tarea de Historia',
    'Torneo Intercursos',
    'Reunion de Padres',
    'Feria del Libro',
    'Club Ambiental',
    'Obra de Teatro'
);

INSERT INTO "ACTIVIDADES_ESCOLARES" (
    "TIPO_ACTIVIDAD_ID",
    "TITULO",
    "DESCRIPCION",
    "FECHA",
    "FECHA_FIN",
    "HORA",
    "UBICACION",
    "ACTIVO"
)
SELECT t."ID", s."TITULO", s."DESCRIPCION", s."FECHA", s."FECHA_FIN", s."HORA", s."UBICACION", TRUE
FROM (
    VALUES
        ('INSTITUCIONAL', 'Ingreso de estudiantes', 'Ingreso general de estudiantes al establecimiento a las 08:30.', DATE '2026-03-04', DATE '2026-03-04', TIME '08:30', 'Acceso principal'),
        ('ACADEMICA', 'Comienzo de clases y nivelacion', 'Inicio formal de clases y actividades de nivelacion para todos los cursos.', DATE '2026-03-05', DATE '2026-03-05', NULL, 'Todas las salas'),
        ('SOCIAL', 'Culto de apertura y presentacion', 'Culto de apertura del anio escolar y presentacion institucional.', DATE '2026-03-08', DATE '2026-03-08', TIME '11:00', 'Salon principal'),
        ('SOCIAL', 'Dia de la Mujer y reunion de apoderados', 'Conmemoracion institucional y reunion general de apoderados a las 18:30.', DATE '2026-03-09', DATE '2026-03-09', TIME '18:30', 'Patio cubierto'),
        ('INSTITUCIONAL', 'Actividades breves Semana Santa', 'Actividades breves de Semana Santa con clases normales en todos los niveles.', DATE '2026-03-30', DATE '2026-04-02', NULL, 'Establecimiento'),
        ('INSTITUCIONAL', 'Inicio inscripcion examenes libres Mineduc', 'Apertura del proceso de inscripcion para examenes libres.', DATE '2026-04-01', DATE '2026-04-01', NULL, 'Secretaria academica'),
        ('INSTITUCIONAL', 'Feriado Viernes Santo', 'Suspension de actividades por feriado religioso.', DATE '2026-04-03', DATE '2026-04-03', NULL, 'Sin clases'),

        ('ACADEMICA', 'Evaluacion Lectoescritura Pre Kinder', 'Trazos curvos y rectos; reconocer y escribir vocales A-E.', DATE '2026-03-27', DATE '2026-03-27', NULL, 'Sala Pre Kinder'),
        ('ACADEMICA', 'Evaluacion Matematicas Pre Kinder', 'Escritura numeros 1 al 5 y ubicacion espacial.', DATE '2026-03-30', DATE '2026-03-30', NULL, 'Sala Pre Kinder'),

        ('ACADEMICA', 'Evaluacion Lectoescritura Kinder', 'Dictado de vocales, reconocimiento inicial y final de vocales y trazos.', DATE '2026-03-27', DATE '2026-03-27', NULL, 'Sala Kinder'),
        ('ACADEMICA', 'Evaluacion Matematicas Kinder', 'Escritura numeros 1 al 10, secuencia numerica, conteo y ubicacion espacial.', DATE '2026-03-30', DATE '2026-03-30', NULL, 'Sala Kinder'),

        ('ACADEMICA', 'Evaluacion Ciencias 1 Basico', 'Evaluacion de Ciencias sobre los sentidos.', DATE '2026-03-26', DATE '2026-03-26', NULL, 'Sala 1 Basico'),
        ('ACADEMICA', 'Evaluacion Lenguaje 1 Basico', 'Dictado de vocales y consonantes M-P, identificacion de sonidos y lectura de silabas.', DATE '2026-03-27', DATE '2026-03-27', NULL, 'Sala 1 Basico'),
        ('ACADEMICA', 'Evaluacion Matematicas 1 Basico', 'Numeros del 1 al 20, conteo, secuencia, adicion y ubicacion espacial.', DATE '2026-03-30', DATE '2026-03-30', NULL, 'Sala 1 Basico'),
        ('ACADEMICA', 'Evaluacion Historia 1 Basico', 'Ordenar secuencias temporales antes y despues.', DATE '2026-03-31', DATE '2026-03-31', NULL, 'Sala 1 Basico'),

        ('ACADEMICA', 'Guia evaluada Historia 3 Basico', 'Pueblos indigenas, espanoles e inmigrantes: ubicacion y aportes.', DATE '2026-03-11', DATE '2026-03-11', NULL, 'Sala 3 Basico'),
        ('ACADEMICA', 'Guia evaluada Ciencias Naturales 3 Basico', 'Ciclo de vida de animales, organos del cuerpo humano y ciclo del agua.', DATE '2026-03-13', DATE '2026-03-13', NULL, 'Sala 3 Basico'),
        ('ACADEMICA', 'Prueba de Lenguaje 3 Basico', 'Leyendas, textos informativos, cuentos y fabulas.', DATE '2026-03-19', DATE '2026-03-19', NULL, 'Sala 3 Basico'),

        ('ACADEMICA', 'Guia evaluada Historia 4 Basico', 'Pueblo romano y griego; hemisferios, continentes y zonas geograficas.', DATE '2026-03-11', DATE '2026-03-11', NULL, 'Sala 4 Basico'),
        ('ACADEMICA', 'Guia evaluada Ciencias 4 Basico', 'Clasificacion de alimentos, plantas y seres vivos de Chile.', DATE '2026-03-13', DATE '2026-03-13', NULL, 'Sala 4 Basico'),
        ('ACADEMICA', 'Prueba de Lenguaje 4 Basico', 'Leyendas, textos informativos, cuentos y fabulas.', DATE '2026-03-19', DATE '2026-03-19', NULL, 'Sala 4 Basico'),

        ('ACADEMICA', 'Guia evaluada Historia 5 Basico', 'Civilizacion inca, maya y azteca; organizacion politica de Chile.', DATE '2026-03-12', DATE '2026-03-12', NULL, 'Sala 5 Basico'),
        ('ACADEMICA', 'Guia evaluada Ciencias 5 Basico', 'Ecosistemas, cadenas alimenticias y sistemas del cuerpo.', DATE '2026-03-13', DATE '2026-03-13', NULL, 'Sala 5 Basico'),
        ('ACADEMICA', 'Prueba de Lenguaje 5 Basico', 'Leyendas, textos informativos, cuentos y fabulas.', DATE '2026-03-18', DATE '2026-03-18', NULL, 'Sala 5 Basico'),

        ('ACADEMICA', 'Guia evaluada Historia 6 Basico', 'Conquista de America y Chile; zonas de Chile y recursos.', DATE '2026-03-12', DATE '2026-03-12', NULL, 'Sala 6 Basico'),
        ('ACADEMICA', 'Guia evaluada Ciencias 6 Basico', 'Organizacion de los seres vivos, nutrientes y materiales conductores.', DATE '2026-03-13', DATE '2026-03-13', NULL, 'Sala 6 Basico'),
        ('ACADEMICA', 'Prueba de Lenguaje 6 Basico', 'Leyendas, textos informativos, cuentos y fabulas.', DATE '2026-03-18', DATE '2026-03-18', NULL, 'Sala 6 Basico'),

        ('ACADEMICA', 'Examen Matematicas', 'Evaluacion mensual de la asignatura para 6 Basico.', DATE '2026-04-08', DATE '2026-04-08', TIME '08:00', 'Sala 12'),
        ('INSTITUCIONAL', 'Reunion Docentes', 'Coordinacion pedagogica del inicio de mes.', DATE '2026-04-10', DATE '2026-04-10', TIME '13:30', 'Sala de reuniones'),
        ('ACADEMICA', 'Laboratorio Ciencias', 'Practica guiada en laboratorio para 7 Basico.', DATE '2026-04-14', DATE '2026-04-14', TIME '10:00', 'Laboratorio central'),
        ('CULTURAL', 'Proyecto Arte', 'Entrega intermedia del proyecto artistico semestral.', DATE '2026-04-16', DATE '2026-04-16', NULL, 'Sala de arte'),
        ('ACADEMICA', 'Tarea de Historia', 'Entrega de maqueta sobre patrimonio nacional.', DATE '2026-04-20', DATE '2026-04-20', NULL, 'Aula 8'),
        ('DEPORTIVA', 'Torneo Intercursos', 'Encuentro deportivo recreativo por alianzas.', DATE '2026-04-24', DATE '2026-04-24', TIME '14:00', 'Patio central'),
        ('SOCIAL', 'Reunion de Padres', 'Encuentro general de apoderados del ciclo basico.', DATE '2026-04-27', DATE '2026-04-27', TIME '17:00', 'Salon principal'),
        ('CULTURAL', 'Feria del Libro', 'Actividad transversal de lectura y presentaciones estudiantiles.', DATE '2026-04-23', DATE '2026-04-24', TIME '09:00', 'Biblioteca'),
        ('DEPORTIVA', 'Club Ambiental', 'Jornada de trabajo del club ambiental y huerto escolar.', DATE '2026-04-29', DATE '2026-04-29', TIME '15:00', 'Patio principal'),
        ('CULTURAL', 'Obra de Teatro', 'Presentacion abierta a la comunidad escolar.', DATE '2026-04-30', DATE '2026-04-30', TIME '18:00', 'Auditorio')
) AS s("CODIGO_TIPO", "TITULO", "DESCRIPCION", "FECHA", "FECHA_FIN", "HORA", "UBICACION")
JOIN "TIPOS_ACTIVIDAD" t ON t."CODIGO" = s."CODIGO_TIPO";
