BEGIN;

ALTER TABLE "PROFESOR_ASIGNATURAS"
    ADD COLUMN IF NOT EXISTS "ASIGNATURA_ID" BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM "ASIGNATURAS"
        WHERE UPPER(TRIM("NOMBRE")) = 'TECNOLOGIA'
    ) THEN
        INSERT INTO "ASIGNATURAS" (
            "CODIGO",
            "NOMBRE",
            "AREA",
            "COLOR_HEX",
            "ACTIVA",
            "DESCRIPCION",
            "NIVEL_REFERENCIA",
            "HORAS_SUGERIDAS"
        )
        VALUES (
            'TEC',
            'Tecnologia',
            'Tecnologia',
            '#8BA7E8',
            TRUE,
            'Asignatura de tecnologia aplicada al aprendizaje escolar.',
            'Ensenanza basica',
            2
        );
    END IF;
END $$;

UPDATE "PROFESOR_ASIGNATURAS" pa
SET "ASIGNATURA_ID" = a."ID"
FROM "ASIGNATURAS" a
WHERE pa."ASIGNATURA_ID" IS NULL
  AND UPPER(TRIM(pa."ASIGNATURA")) = UPPER(TRIM(a."NOMBRE"));

UPDATE "PROFESOR_ASIGNATURAS"
SET "ASIGNATURA_ID" = (
    SELECT "ID" FROM "ASIGNATURAS" WHERE "NOMBRE" = 'Matematica'
)
WHERE "ASIGNATURA_ID" IS NULL
  AND UPPER(TRIM("ASIGNATURA")) = 'MATEMATICAS';

UPDATE "PROFESOR_ASIGNATURAS"
SET "ASIGNATURA_ID" = (
    SELECT "ID" FROM "ASIGNATURAS" WHERE "NOMBRE" = 'Tecnologia'
)
WHERE "ASIGNATURA_ID" IS NULL
  AND UPPER(TRIM("ASIGNATURA")) = 'TECNOLOGIA';

UPDATE "PROFESOR_ASIGNATURAS" pa
SET "ASIGNATURA" = a."NOMBRE"
FROM "ASIGNATURAS" a
WHERE pa."ASIGNATURA_ID" = a."ID";

ALTER TABLE "PROFESOR_ASIGNATURAS"
    DROP CONSTRAINT IF EXISTS "FK_PROFESOR_ASIGNATURAS_PROFESORES";

ALTER TABLE "PROFESOR_ASIGNATURAS"
    ADD CONSTRAINT "FK_PROFESOR_ASIGNATURAS_PROFESORES_REAL"
    FOREIGN KEY ("PROFESOR_ID") REFERENCES "PROFESORES"("ID");

ALTER TABLE "PROFESOR_ASIGNATURAS"
    DROP CONSTRAINT IF EXISTS "FK_PROFESOR_ASIGNATURAS_ASIGNATURA";

ALTER TABLE "PROFESOR_ASIGNATURAS"
    ADD CONSTRAINT "FK_PROFESOR_ASIGNATURAS_ASIGNATURA"
    FOREIGN KEY ("ASIGNATURA_ID") REFERENCES "ASIGNATURAS"("ID");

ALTER TABLE "CURSO_DOCENTES"
    DROP CONSTRAINT IF EXISTS "FK_CURSO_DOCENTES_PROFESOR";

ALTER TABLE "CURSO_DOCENTES"
    DROP CONSTRAINT IF EXISTS "FK_CURSO_DOCENTES_ASISTENTE";

ALTER TABLE "CURSO_DOCENTES"
    ADD CONSTRAINT "FK_CURSO_DOCENTES_PROFESOR_REAL"
    FOREIGN KEY ("PROFESOR_ID") REFERENCES "PROFESORES"("ID");

ALTER TABLE "CURSO_DOCENTES"
    ADD CONSTRAINT "FK_CURSO_DOCENTES_ASISTENTE_REAL"
    FOREIGN KEY ("ASISTENTE_ID") REFERENCES "PROFESORES"("ID");

COMMIT;
