BEGIN;

-- Consolida el duplicado funcional de Maria Gonzalez Rojas:
-- docente canónico: PROFESORES.ID = 2
-- docente duplicado sin cargas: PROFESORES.ID = 4

UPDATE "USUARIOS"
SET "PERSONA_ID" = 5
WHERE "PERSONA_ID" = 2;

UPDATE "ASIGNACIONES"
SET "PROFESOR_PERSONA_ID" = 5
WHERE "PROFESOR_PERSONA_ID" = 2;

INSERT INTO "PROFESOR_ASIGNATURAS" ("PROFESOR_ID", "ASIGNATURA_ID", "ASIGNATURA", "ACTIVO")
SELECT
    2,
    pa."ASIGNATURA_ID",
    pa."ASIGNATURA",
    COALESCE(pa."ACTIVO", TRUE)
FROM "PROFESOR_ASIGNATURAS" pa
WHERE pa."PROFESOR_ID" = 4
  AND NOT EXISTS (
      SELECT 1
      FROM "PROFESOR_ASIGNATURAS" canon
      WHERE canon."PROFESOR_ID" = 2
        AND (
            canon."ASIGNATURA_ID" = pa."ASIGNATURA_ID"
            OR UPPER(TRIM(COALESCE(canon."ASIGNATURA", ''))) = UPPER(TRIM(COALESCE(pa."ASIGNATURA", '')))
        )
  );

DELETE FROM "PROFESOR_CONTACTOS_EMERGENCIA"
WHERE "PROFESOR_ID" = 2;

INSERT INTO "PROFESOR_CONTACTOS_EMERGENCIA" ("PROFESOR_ID", "NOMBRE_COMPLETO", "RELACION", "TELEFONO", "ACTIVO")
SELECT
    2,
    dup_person."NOMBRES" || ' ' || dup_person."APELLIDOS",
    'Contacto institucional',
    dup_person."TELEFONO",
    TRUE
FROM "PROFESORES" p_dup
JOIN "PERSONAS" dup_person
  ON dup_person."ID" = p_dup."PERSONA_ID"
WHERE p_dup."ID" = 4;

DELETE FROM "PROFESOR_CONTACTOS_EMERGENCIA"
WHERE "PROFESOR_ID" = 4;

DELETE FROM "PROFESOR_ASIGNATURAS"
WHERE "PROFESOR_ID" = 4;

DELETE FROM "PROFESORES"
WHERE "ID" = 4;

UPDATE "PROFESORES"
SET "PERSONA_ID" = 5
WHERE "ID" = 2;

DELETE FROM "PERSONAS"
WHERE "ID" = 2;

COMMIT;
