CREATE TABLE IF NOT EXISTS "CURSOS_MAESTROS" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CODIGO" VARCHAR(30) NOT NULL UNIQUE,
    "DESCRIPCION" VARCHAR(120) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO "CURSOS_MAESTROS" ("CODIGO", "DESCRIPCION", "ACTIVO")
SELECT * FROM (
    VALUES
        ('CUR-1A', 'Primero Basico A', TRUE),
        ('CUR-1B', 'Primero Basico B', TRUE),
        ('CUR-2A', 'Segundo Basico A', TRUE),
        ('CUR-2B', 'Segundo Basico B', TRUE),
        ('CUR-3A', 'Tercero Basico A', TRUE),
        ('CUR-3B', 'Tercero Basico B', TRUE),
        ('CUR-4A', 'Cuarto Basico A', TRUE),
        ('CUR-4B', 'Cuarto Basico B', TRUE),
        ('CUR-5A', 'Quinto Basico A', TRUE),
        ('CUR-5B', 'Quinto Basico B', TRUE),
        ('CUR-6A', 'Sexto Basico A', TRUE),
        ('CUR-6B', 'Sexto Basico B', TRUE),
        ('CUR-7A', 'Septimo Basico A', TRUE),
        ('CUR-7B', 'Septimo Basico B', TRUE),
        ('CUR-8A', 'Octavo Basico A', TRUE),
        ('CUR-8B', 'Octavo Basico B', TRUE)
) AS v("CODIGO", "DESCRIPCION", "ACTIVO")
WHERE NOT EXISTS (
    SELECT 1 FROM "CURSOS_MAESTROS" cm WHERE cm."CODIGO" = v."CODIGO"
);
