SELECT "ID", "NOMBRE", "ANIO_ESCOLAR"
FROM "CURSOS"
WHERE "ACTIVO" = TRUE
ORDER BY "NOMBRE";

\d "MATRICULAS"

SELECT
  m."ID",
  a."ID" AS alumno_id,
  a."NOMBRE",
  a."APELLIDOS",
  c."NOMBRE" AS curso
FROM "MATRICULAS" m
JOIN "ALUMNOS" a ON a."ID" = m."ALUMNO_ID"
JOIN "CURSOS" c ON c."ID" = m."CURSO_ID"
WHERE m."ACTIVA" = TRUE
ORDER BY c."NOMBRE", a."NOMBRE";
