SELECT 'CURSOS' AS tabla, "ID", "NOMBRE" AS valor
FROM "CURSOS"
WHERE "NOMBRE" LIKE '%Â%' OR "NOMBRE" LIKE '%Ã%'
UNION ALL
SELECT 'CURSOS_MAESTROS' AS tabla, "ID", COALESCE("DESCRIPCION", '') AS valor
FROM "CURSOS_MAESTROS"
WHERE COALESCE("DESCRIPCION", '') LIKE '%Â%' OR COALESCE("DESCRIPCION", '') LIKE '%Ã%'
UNION ALL
SELECT 'ASIGNATURAS' AS tabla, "ID", "NOMBRE" AS valor
FROM "ASIGNATURAS"
WHERE "NOMBRE" LIKE '%Â%' OR "NOMBRE" LIKE '%Ã%'
UNION ALL
SELECT 'ASIGNATURAS_DESC' AS tabla, "ID", COALESCE("DESCRIPCION", '') AS valor
FROM "ASIGNATURAS"
WHERE COALESCE("DESCRIPCION", '') LIKE '%Â%' OR COALESCE("DESCRIPCION", '') LIKE '%Ã%'
UNION ALL
SELECT 'PROFESORES_CATALOGO' AS tabla, "ID", COALESCE("NOMBRE", '') || ' ' || COALESCE("APELLIDO", '') AS valor
FROM "PROFESORES_CATALOGO"
WHERE COALESCE("NOMBRE", '') LIKE '%Â%' OR COALESCE("NOMBRE", '') LIKE '%Ã%'
   OR COALESCE("APELLIDO", '') LIKE '%Â%' OR COALESCE("APELLIDO", '') LIKE '%Ã%'
ORDER BY tabla, "ID";
