ALTER TABLE "CLASES_PLANIFICACION_DOCUMENTOS"
    ADD COLUMN IF NOT EXISTS "UNIDAD_ID" BIGINT NULL,
    ADD COLUMN IF NOT EXISTS "TIPO_ARCHIVO" VARCHAR(20) NOT NULL DEFAULT 'OTRO',
    ADD COLUMN IF NOT EXISTS "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN IF NOT EXISTS "ELIMINADO" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "CREADO_POR_USUARIO_ID" BIGINT NULL;

UPDATE "CLASES_PLANIFICACION_DOCUMENTOS" docs
SET
    "UNIDAD_ID" = cp."UNIDAD_ID",
    "TIPO_ARCHIVO" = CASE
        WHEN LOWER(docs."EXTENSION") IN ('doc', 'docx') THEN 'WORD'
        WHEN LOWER(docs."EXTENSION") = 'pdf' THEN 'PDF'
        WHEN LOWER(docs."EXTENSION") IN ('ppt', 'pptx') THEN 'PPT'
        ELSE 'OTRO'
    END,
    "ESTADO" = COALESCE(docs."ESTADO", 'ACTIVO'),
    "ELIMINADO" = COALESCE(docs."ELIMINADO", FALSE),
    "CREADO_POR_USUARIO_ID" = COALESCE(docs."CREADO_POR_USUARIO_ID", cp."CREADO_POR_USUARIO_ID")
FROM "CLASES_PLANIFICACION" cp
WHERE cp."ID" = docs."CLASE_ID";

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_CLASES_PLANIFICACION_DOCUMENTOS_UNIDAD'
    ) THEN
        ALTER TABLE "CLASES_PLANIFICACION_DOCUMENTOS"
            ADD CONSTRAINT "FK_CLASES_PLANIFICACION_DOCUMENTOS_UNIDAD"
            FOREIGN KEY ("UNIDAD_ID") REFERENCES "UNIDADES_PLANIFICACION" ("ID");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_CLASES_PLANIFICACION_DOCUMENTOS_CREADO_POR'
    ) THEN
        ALTER TABLE "CLASES_PLANIFICACION_DOCUMENTOS"
            ADD CONSTRAINT "FK_CLASES_PLANIFICACION_DOCUMENTOS_CREADO_POR"
            FOREIGN KEY ("CREADO_POR_USUARIO_ID") REFERENCES "USUARIOS" ("ID");
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IDX_CLASES_PLANIFICACION_DOCUMENTOS_UNIDAD_ID"
    ON "CLASES_PLANIFICACION_DOCUMENTOS" ("UNIDAD_ID");

CREATE INDEX IF NOT EXISTS "IDX_CLASES_PLANIFICACION_DOCUMENTOS_CLASE_ID"
    ON "CLASES_PLANIFICACION_DOCUMENTOS" ("CLASE_ID");

CREATE INDEX IF NOT EXISTS "IDX_CLASES_PLANIFICACION_DOCUMENTOS_TIPO_ARCHIVO"
    ON "CLASES_PLANIFICACION_DOCUMENTOS" ("TIPO_ARCHIVO");

CREATE INDEX IF NOT EXISTS "IDX_CLASES_PLANIFICACION_DOCUMENTOS_ELIMINADO"
    ON "CLASES_PLANIFICACION_DOCUMENTOS" ("ELIMINADO");

INSERT INTO "CLASES_PLANIFICACION_DOCUMENTOS" (
    "CLASE_ID",
    "UNIDAD_ID",
    "NOMBRE_ORIGINAL",
    "NOMBRE_ARCHIVO",
    "EXTENSION",
    "MIME_TYPE",
    "PESO_BYTES",
    "RUTA_ARCHIVO",
    "TIPO_ARCHIVO",
    "VISIBLE_ALUMNOS",
    "ESTADO",
    "ELIMINADO",
    "CREADO_POR_USUARIO_ID"
)
SELECT
    cp."ID",
    cp."UNIDAD_ID",
    'Guia_fracciones_U1.docx',
    'guia-fracciones-u1-demo.docx',
    'docx',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    131072,
    'uploads/planning-classes/guia-fracciones-u1-demo.docx',
    'WORD',
    TRUE,
    'ACTIVO',
    FALSE,
    cp."CREADO_POR_USUARIO_ID"
FROM "CLASES_PLANIFICACION" cp
WHERE NOT EXISTS (
    SELECT 1
    FROM "CLASES_PLANIFICACION_DOCUMENTOS" docs
    WHERE docs."NOMBRE_ARCHIVO" = 'guia-fracciones-u1-demo.docx'
);
