ALTER TABLE "PERSONAS"
    ADD COLUMN IF NOT EXISTS "FECHA_NACIMIENTO" DATE,
    ADD COLUMN IF NOT EXISTS "GENERO" VARCHAR(30);

ALTER TABLE "PROFESORES"
    ADD COLUMN IF NOT EXISTS "TITULO_PROFESIONAL" VARCHAR(180),
    ADD COLUMN IF NOT EXISTS "TIPO_CONTRATO" VARCHAR(60),
    ADD COLUMN IF NOT EXISTS "HORAS_SEMANALES" INTEGER,
    ADD COLUMN IF NOT EXISTS "FECHA_INGRESO" DATE,
    ADD COLUMN IF NOT EXISTS "ESTADO_DOCENTE" VARCHAR(40);

CREATE TABLE IF NOT EXISTS "PROFESOR_ASIGNATURAS" (
    "ID" BIGSERIAL PRIMARY KEY,
    "PROFESOR_ID" BIGINT NOT NULL REFERENCES "PROFESORES"("ID"),
    "ASIGNATURA_ID" BIGINT NOT NULL REFERENCES "ASIGNATURAS"("ID"),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "PROFESOR_CONTACTOS_EMERGENCIA" (
    "ID" BIGSERIAL PRIMARY KEY,
    "PROFESOR_ID" BIGINT NOT NULL REFERENCES "PROFESORES"("ID"),
    "NOMBRE_COMPLETO" VARCHAR(160) NOT NULL,
    "RELACION" VARCHAR(80) NOT NULL,
    "TELEFONO" VARCHAR(30) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

UPDATE "PROFESORES"
SET
    "TITULO_PROFESIONAL" = COALESCE(NULLIF("TITULO_PROFESIONAL", ''), NULLIF("ESPECIALIDAD", ''), 'Profesor de aula'),
    "TIPO_CONTRATO" = COALESCE(NULLIF("TIPO_CONTRATO", ''), 'Jornada completa'),
    "HORAS_SEMANALES" = COALESCE("HORAS_SEMANALES", 38),
    "FECHA_INGRESO" = COALESCE("FECHA_INGRESO", CURRENT_DATE),
    "ESTADO_DOCENTE" = COALESCE(NULLIF("ESTADO_DOCENTE", ''), CASE WHEN "ACTIVO" THEN 'Activo' ELSE 'Inactivo' END);

UPDATE "PERSONAS"
SET
    "GENERO" = COALESCE(NULLIF("GENERO", ''), 'No especificado')
WHERE EXISTS (
    SELECT 1
    FROM "PROFESORES" pr
    WHERE pr."PERSONA_ID" = "PERSONAS"."ID"
);

INSERT INTO "PROFESOR_ASIGNATURAS" ("PROFESOR_ID", "ASIGNATURA_ID", "ACTIVO")
SELECT DISTINCT
    cd."PROFESOR_ID",
    cd."ASIGNATURA_ID",
    TRUE
FROM "CARGAS_DOCENTES" cd
WHERE cd."ACTIVA" = TRUE
  AND NOT EXISTS (
      SELECT 1
      FROM "PROFESOR_ASIGNATURAS" pa
      WHERE pa."PROFESOR_ID" = cd."PROFESOR_ID"
        AND pa."ASIGNATURA_ID" = cd."ASIGNATURA_ID"
  );

INSERT INTO "PROFESOR_CONTACTOS_EMERGENCIA" ("PROFESOR_ID", "NOMBRE_COMPLETO", "RELACION", "TELEFONO", "ACTIVO")
SELECT
    pr."ID",
    pe."NOMBRES" || ' ' || pe."APELLIDOS",
    'Contacto institucional',
    COALESCE(NULLIF(pe."TELEFONO", ''), '+56 9 0000 0000'),
    TRUE
FROM "PROFESORES" pr
JOIN "PERSONAS" pe ON pe."ID" = pr."PERSONA_ID"
WHERE NOT EXISTS (
    SELECT 1
    FROM "PROFESOR_CONTACTOS_EMERGENCIA" pce
    WHERE pce."PROFESOR_ID" = pr."ID"
      AND pce."ACTIVO" = TRUE
);
