BEGIN;

DELETE FROM "CURSO_ALUMNOS" ca
WHERE EXISTS (
    SELECT 1
    FROM "MATRICULAS" m
    WHERE m."ALUMNO_ID" = ca."ALUMNO_ID"
)
AND NOT EXISTS (
    SELECT 1
    FROM "MATRICULAS" m
    WHERE m."ALUMNO_ID" = ca."ALUMNO_ID"
      AND m."CURSO_ID" = ca."CURSO_ID"
      AND m."ACTIVA" = TRUE
);

INSERT INTO "CURSO_ALUMNOS" ("CURSO_ID", "ALUMNO_ID", "FECHA_ASIGNACION", "ACTIVO")
SELECT m."CURSO_ID", m."ALUMNO_ID", COALESCE(m."FECHA_MATRICULA", CURRENT_DATE), TRUE
FROM "MATRICULAS" m
WHERE m."ACTIVA" = TRUE
ON CONFLICT ("ALUMNO_ID")
DO UPDATE SET
    "CURSO_ID" = EXCLUDED."CURSO_ID",
    "ACTIVO" = TRUE,
    "FECHA_ASIGNACION" = EXCLUDED."FECHA_ASIGNACION";

COMMIT;
