BEGIN;

ALTER TABLE "PROFESOR_ASIGNATURAS"
    ADD COLUMN IF NOT EXISTS "ASIGNATURA_ID" BIGINT;

UPDATE "PROFESOR_ASIGNATURAS" pa
SET "ASIGNATURA_ID" = a."ID"
FROM "ASIGNATURAS" a
WHERE pa."ASIGNATURA_ID" IS NULL
  AND UPPER(TRIM(COALESCE(pa."ASIGNATURA", ''))) = UPPER(TRIM(a."NOMBRE"));

DELETE FROM "PROFESOR_ASIGNATURAS" pa
WHERE EXISTS (
    SELECT 1
    FROM "CARGAS_DOCENTES" cd
    WHERE cd."PROFESOR_ID" = pa."PROFESOR_ID"
      AND COALESCE(cd."ACTIVA", TRUE) = TRUE
);

INSERT INTO "PROFESOR_ASIGNATURAS" ("PROFESOR_ID", "ASIGNATURA_ID", "ASIGNATURA", "ACTIVO")
SELECT DISTINCT
    cd."PROFESOR_ID",
    a."ID",
    a."NOMBRE",
    TRUE
FROM "CARGAS_DOCENTES" cd
JOIN "ASIGNATURAS" a
  ON a."ID" = cd."ASIGNATURA_ID"
WHERE COALESCE(cd."ACTIVA", TRUE) = TRUE
  AND NOT EXISTS (
      SELECT 1
      FROM "PROFESOR_ASIGNATURAS" pa
      WHERE pa."PROFESOR_ID" = cd."PROFESOR_ID"
        AND (
            pa."ASIGNATURA_ID" = a."ID"
            OR UPPER(TRIM(COALESCE(pa."ASIGNATURA", ''))) = UPPER(TRIM(a."NOMBRE"))
        )
  );

UPDATE "PROFESOR_ASIGNATURAS" pa
SET "ASIGNATURA" = a."NOMBRE"
FROM "ASIGNATURAS" a
WHERE pa."ASIGNATURA_ID" = a."ID"
  AND COALESCE(pa."ASIGNATURA", '') <> a."NOMBRE";

COMMIT;
