BEGIN;

TRUNCATE TABLE "ASIGNACIONES" RESTART IDENTITY;

INSERT INTO "ASIGNACIONES" (
    "CURSO_ID",
    "PROFESOR_PERSONA_ID",
    "DIA_SEMANA",
    "HORA_INICIO",
    "HORA_FIN",
    "ACTIVO"
)
SELECT
    cd."CURSO_ID",
    p."PERSONA_ID",
    bh."DIA_SEMANA",
    bh."HORA_INICIO",
    bh."HORA_FIN",
    TRUE
FROM "HORARIOS_CARGAS" hc
JOIN "CARGAS_DOCENTES" cd ON cd."ID" = hc."CARGA_DOCENTE_ID"
JOIN "PROFESORES" p ON p."ID" = cd."PROFESOR_ID"
JOIN "BLOQUES_HORARIOS" bh ON bh."ID" = hc."BLOQUE_HORARIO_ID"
WHERE cd."ACTIVA" = TRUE
  AND bh."ACTIVO" = TRUE
  AND bh."TIPO_BLOQUE" = 'CLASE';

COMMIT;
