BEGIN;

TRUNCATE TABLE "PROFESORES_CATALOGO" RESTART IDENTITY;

INSERT INTO "PROFESORES_CATALOGO" ("ID", "NOMBRE", "RUD", "APELLIDO", "DIRECCION", "EMAIL", "ACTIVO")
SELECT
    p."ID",
    pe."NOMBRES",
    pe."RUN",
    pe."APELLIDOS",
    pe."DIRECCION",
    pe."CORREO_ELECTRONICO",
    p."ACTIVO"
FROM "PROFESORES" p
JOIN "PERSONAS" pe
  ON pe."ID" = p."PERSONA_ID"
ORDER BY p."ID";

SELECT setval(
    pg_get_serial_sequence('"PROFESORES_CATALOGO"', 'ID'),
    COALESCE((SELECT MAX("ID") FROM "PROFESORES_CATALOGO"), 1),
    true
);

COMMIT;
