BEGIN;

DELETE FROM "CURSO_ASIGNATURAS" ca
WHERE EXISTS (
    SELECT 1
    FROM "CARGAS_DOCENTES" cd
    WHERE cd."CURSO_ID" = ca."CURSO_ID"
      AND cd."ACTIVA" = TRUE
)
AND NOT EXISTS (
    SELECT 1
    FROM "CARGAS_DOCENTES" cd
    WHERE cd."CURSO_ID" = ca."CURSO_ID"
      AND cd."ASIGNATURA_ID" = ca."ASIGNATURA_ID"
      AND cd."ACTIVA" = TRUE
);

INSERT INTO "CURSO_ASIGNATURAS" ("CURSO_ID", "ASIGNATURA_ID", "ACTIVA")
SELECT DISTINCT cd."CURSO_ID", cd."ASIGNATURA_ID", TRUE
FROM "CARGAS_DOCENTES" cd
WHERE cd."ACTIVA" = TRUE
ON CONFLICT ("CURSO_ID", "ASIGNATURA_ID")
DO UPDATE SET "ACTIVA" = TRUE;

COMMIT;
