SELECT 'CURSOS' AS tabla, "ID"::text AS id, "NOMBRE" AS valor
FROM "CURSOS"
WHERE "NOMBRE" LIKE '%Â%' OR "NOMBRE" LIKE '%Ã%'
UNION ALL
SELECT 'ASIGNATURAS', "ID"::text, "NOMBRE"
FROM "ASIGNATURAS"
WHERE "NOMBRE" LIKE '%Â%' OR "NOMBRE" LIKE '%Ã%'
UNION ALL
SELECT 'ASIGNATURAS_DESC', "ID"::text, "DESCRIPCION"
FROM "ASIGNATURAS"
WHERE COALESCE("DESCRIPCION", '') LIKE '%Â%' OR COALESCE("DESCRIPCION", '') LIKE '%Ã%'
UNION ALL
SELECT 'PROFESORES', "ID"::text, COALESCE("ESPECIALIDAD", '')
FROM "PROFESORES"
WHERE COALESCE("ESPECIALIDAD", '') LIKE '%Â%' OR COALESCE("ESPECIALIDAD", '') LIKE '%Ã%'
UNION ALL
SELECT 'PERSONAS', "ID"::text, COALESCE("DIRECCION", '')
FROM "PERSONAS"
WHERE COALESCE("DIRECCION", '') LIKE '%Â%' OR COALESCE("DIRECCION", '') LIKE '%Ã%'
ORDER BY tabla, id;
