SELECT DISTINCT c."ID", c."NOMBRE", c."ANIO_ESCOLAR"
FROM "CURSOS" c
JOIN "MATRICULAS" m ON m."CURSO_ID" = c."ID"
WHERE c."ACTIVO" = TRUE
  AND m."ACTIVA" = TRUE
ORDER BY
  CASE
    WHEN UPPER(c."NOMBRE") LIKE '%PK%' THEN 0
    WHEN UPPER(c."NOMBRE") LIKE '%KINDER%' THEN 1
    ELSE 2
  END,
  c."NOMBRE";
