SELECT p."ID" AS profesor_id, pe."RUN", pe."NOMBRES", pe."APELLIDOS", pe."CORREO_ELECTRONICO", pe."TELEFONO", pe."DIRECCION"
FROM "PROFESORES" p
JOIN "PERSONAS" pe ON pe."ID" = p."PERSONA_ID"
ORDER BY p."ID";
