SELECT pe."RUN", pe."NOMBRES", pe."APELLIDOS", COUNT(*) AS total
FROM "PROFESORES" p
JOIN "PERSONAS" pe ON pe."ID" = p."PERSONA_ID"
GROUP BY pe."RUN", pe."NOMBRES", pe."APELLIDOS"
HAVING COUNT(*) > 1
ORDER BY total DESC, pe."NOMBRES", pe."APELLIDOS";
