SELECT p."ID", pe."RUN", pe."NOMBRES", pe."APELLIDOS", pe."CORREO_ELECTRONICO", pe."TELEFONO", pe."DIRECCION"
FROM "PROFESORES" p
JOIN "PERSONAS" pe ON pe."ID" = p."PERSONA_ID"
WHERE p."ID" IN (1,2,4);
