SELECT pa."PROFESOR_ID",
       pa."ASIGNATURA"
FROM public."PROFESOR_ASIGNATURAS" pa
LEFT JOIN public."ASIGNATURAS" a ON UPPER(TRIM(a."NOMBRE")) = UPPER(TRIM(pa."ASIGNATURA"))
WHERE pa."ACTIVO" = TRUE AND a."ID" IS NULL
ORDER BY pa."PROFESOR_ID", pa."ASIGNATURA";
