SELECT 'PROFESOR_ASIGNATURAS' AS tabla, COUNT(*) AS total FROM "PROFESOR_ASIGNATURAS" WHERE "PROFESOR_ID" = 4
UNION ALL
SELECT 'PROFESOR_CONTACTOS_EMERGENCIA', COUNT(*) FROM "PROFESOR_CONTACTOS_EMERGENCIA" WHERE "PROFESOR_ID" = 4
UNION ALL
SELECT 'CARGAS_DOCENTES', COUNT(*) FROM "CARGAS_DOCENTES" WHERE "PROFESOR_ID" = 4
UNION ALL
SELECT 'CURSO_DOCENTES_PROFESOR', COUNT(*) FROM "CURSO_DOCENTES" WHERE "PROFESOR_ID" = 4
UNION ALL
SELECT 'CURSO_DOCENTES_ASISTENTE', COUNT(*) FROM "CURSO_DOCENTES" WHERE "ASISTENTE_ID" = 4;
