SELECT 'USUARIOS' AS tabla, COUNT(*) AS total FROM "USUARIOS" WHERE "PERSONA_ID" = 2
UNION ALL
SELECT 'USUARIOS', COUNT(*) FROM "USUARIOS" WHERE "PERSONA_ID" = 5
UNION ALL
SELECT 'ASIGNACIONES', COUNT(*) FROM "ASIGNACIONES" WHERE "PROFESOR_PERSONA_ID" = 2
UNION ALL
SELECT 'ASIGNACIONES', COUNT(*) FROM "ASIGNACIONES" WHERE "PROFESOR_PERSONA_ID" = 5;
