SELECT COUNT(*) AS total_periodos FROM "PERIODOS_ACADEMICOS";
SELECT COUNT(*) AS total_curso_asignaturas FROM "CURSO_ASIGNATURAS" WHERE "ACTIVA" = TRUE;
SELECT COUNT(*) AS total_evaluaciones FROM "EVALUACIONES" WHERE "ACTIVA" = TRUE;
SELECT COUNT(*) AS total_calificaciones FROM "CALIFICACIONES" WHERE "ACTIVA" = TRUE;

SELECT
  c."NOMBRE" AS curso,
  s."NOMBRE" AS asignatura,
  COUNT(*) AS evaluaciones
FROM "EVALUACIONES" e
JOIN "CURSOS" c ON c."ID" = e."CURSO_ID"
JOIN "ASIGNATURAS" s ON s."ID" = e."ASIGNATURA_ID"
JOIN "PERIODOS_ACADEMICOS" p ON p."ID" = e."PERIODO_ID"
WHERE p."ANIO" = 2026
  AND p."SEMESTRE" = 1
GROUP BY c."NOMBRE", s."NOMBRE"
ORDER BY c."NOMBRE", s."NOMBRE";

SELECT
  c."NOMBRE" AS curso,
  a."NOMBRE" || ' ' || a."APELLIDOS" AS alumno,
  ROUND(AVG(cal."NOTA"), 2) AS promedio_general
FROM "CALIFICACIONES" cal
JOIN "EVALUACIONES" e ON e."ID" = cal."EVALUACION_ID"
JOIN "CURSOS" c ON c."ID" = e."CURSO_ID"
JOIN "ALUMNOS" a ON a."ID" = cal."ALUMNO_ID"
WHERE cal."ACTIVA" = TRUE
GROUP BY c."NOMBRE", a."NOMBRE", a."APELLIDOS"
ORDER BY c."NOMBRE", alumno;
