SELECT "ID", "CODIGO", "NOMBRE", "ACTIVO"
FROM "CURSOS"
ORDER BY "ID";

SELECT
    a."ID",
    c."NOMBRE" AS "CURSO",
    p."NOMBRES" || ' ' || p."APELLIDOS" AS "PROFESOR",
    a."DIA_SEMANA",
    a."HORA_INICIO",
    a."HORA_FIN"
FROM "ASIGNACIONES" a
JOIN "CURSOS" c ON c."ID" = a."CURSO_ID"
JOIN "PERSONAS" p ON p."ID" = a."PROFESOR_PERSONA_ID"
ORDER BY a."ID";
