SELECT "CODIGO", "NOMBRE", "DESCRIPCION"
FROM "TIPOS_ACTIVIDAD"
WHERE "ACTIVO" = TRUE
ORDER BY "NOMBRE";

SELECT
    a."TITULO",
    a."FECHA",
    a."HORA",
    a."UBICACION",
    t."NOMBRE" AS "TIPO"
FROM "ACTIVIDADES_ESCOLARES" a
JOIN "TIPOS_ACTIVIDAD" t ON t."ID" = a."TIPO_ACTIVIDAD_ID"
WHERE a."ACTIVO" = TRUE
ORDER BY a."FECHA", a."HORA" NULLS LAST;
