SELECT
    pr."CODIGO" AS "PROFESOR",
    a."NOMBRE" AS "ASIGNATURA",
    c."NOMBRE" AS "CURSO",
    cd."HORAS_SEMANALES"
FROM "CARGAS_DOCENTES" cd
JOIN "PROFESORES" pr ON pr."ID" = cd."PROFESOR_ID"
JOIN "ASIGNATURAS" a ON a."ID" = cd."ASIGNATURA_ID"
JOIN "CURSOS" c ON c."ID" = cd."CURSO_ID"
ORDER BY pr."CODIGO", c."NOMBRE";

SELECT
    p."TITULO",
    p."FECHA_CLASE",
    p."ESTADO",
    c."NOMBRE" AS "CURSO"
FROM "PLANIFICACIONES" p
JOIN "CARGAS_DOCENTES" cd ON cd."ID" = p."CARGA_DOCENTE_ID"
JOIN "CURSOS" c ON c."ID" = cd."CURSO_ID"
ORDER BY p."FECHA_CLASE";
