SELECT "CODIGO", "NOMBRE", "NIVEL_LABEL"
FROM "ADMIN_ROLES"
ORDER BY "ORDEN_VISUAL";

SELECT u."USUARIO",
       p."NOMBRES",
       p."APELLIDOS",
       r."CODIGO" AS rol,
       aus."ESTADO",
       aus."ULTIMO_ACCESO_AT"
FROM "ADMIN_USER_SETTINGS" aus
JOIN "USUARIOS" u ON u."ID" = aus."USUARIO_ID"
JOIN "PERSONAS" p ON p."ID" = u."PERSONA_ID"
JOIN "ADMIN_ROLES" r ON r."ID" = aus."ROL_ID"
ORDER BY u."USUARIO";

SELECT "NOMBRE_USUARIO", "TIPO", "ACCION", "OCURRIDO_AT"
FROM "ADMIN_AUDIT_LOGS"
ORDER BY "OCURRIDO_AT" DESC;
