SELECT COUNT(*) AS total_registros FROM "ASISTENCIA_REGISTROS";
SELECT COUNT(*) AS total_detalles FROM "ASISTENCIA_DETALLES";

SELECT c."NOMBRE", COUNT(*) AS registros
FROM "ASISTENCIA_REGISTROS" ar
JOIN "CURSOS" c ON c."ID" = ar."CURSO_ID"
GROUP BY c."NOMBRE"
ORDER BY c."NOMBRE";

SELECT
  c."NOMBRE" AS curso,
  ar."FECHA",
  a."NOMBRE" || ' ' || a."APELLIDOS" AS alumno,
  ad."ESTADO",
  ad."HORA_LLEGADA"
FROM "ASISTENCIA_DETALLES" ad
JOIN "ASISTENCIA_REGISTROS" ar ON ar."ID" = ad."REGISTRO_ID"
JOIN "ALUMNOS" a ON a."ID" = ad."ALUMNO_ID"
JOIN "CURSOS" c ON c."ID" = ar."CURSO_ID"
WHERE ar."FECHA" = DATE '2026-04-03'
ORDER BY c."NOMBRE", alumno;
