server:
  port: 8080

spring:
  application:
    name: backend-api-escolar
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_escolar
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

app:
  security:
    jwt:
      secret: "my-super-secret-key-for-jwt-signing-with-java21-hexagonal-auth"
      expiration-seconds: 3600

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
