spring:
  config:
    activate:
      on-profile: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

